# Copy to build_secrets_local.py (gitignored) and fill in real values.
# Then run: python3 build_workflow.py && python3 build_compose_workflow.py

TAVILY_KEY = "YOUR_TAVILY_KEY"
OPENROUTER_KEY = "YOUR_OPENROUTER_KEY"
ELEVENLABS_KEY = "YOUR_ELEVENLABS_KEY"
CARTESIA_API_KEY = "YOUR_CARTESIA_API_KEY"
CARTESIA_VOICE_ID = "db6b0ed5-d5d3-463d-ae85-518a07d3c2b4"
TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHAT_ID"
RAILWAY_S3_ACCESS_KEY = "YOUR_S3_ACCESS_KEY"
RAILWAY_S3_SECRET_KEY = "YOUR_S3_SECRET_KEY"
